#!/bin/bash
#
# name:
#   search-bcsymbolmap
#
# description:
#   引数として対象のライブラリ名を渡してください. 複数受け付けます.
#   引数なしで実行された場合、Cartfile.resolvedにある全てのライブラリを検索します.
#   このファイル自体はどこにおいても構いませんが、
#   通常carthageを使用するのと同様、プロジェクトのルートディレクトリから実行することを前提としています.
#   tvOSでは以下のように実行してください.
#   `PLATFORM=tvOS search-bcsymbolmap APIKit Himotoki`
#
# author:
#   鈴木 俊裕
#
# Copyright © 2017年 Toshihiro Suzuki All rights reserved.

PLATFORM=${PLATFORM:-iOS}

printBcsymbolmapFiles() {
    tmp0=`mktemp`
    tmp1=`mktemp`

    ls Carthage/Build/${PLATFORM}/*map > $tmp0
    while read l
    do
        echo $l $(sed -n 's/.*-module-name \([A-Za-z_]*\) .*/\1/p' $l | head -1) >> $tmp1
    done < $tmp0
    sort -k2 $tmp1

    rm $tmp0 $tmp1
}

if [ $# -eq 0 ];then
    set -- $(awk '{print $2}' Cartfile.resolved | gsed -rn 's?".*/(.*)"$?\1?p')
fi
for module in $@;do
    if [ "${module}" == "NSObject-Rx" ]; then
        module=NSObject_Rx
    fi
    target=$(printBcsymbolmapFiles | grep $module)
    if [ 0 -eq $(echo $target | sed '/^$/d' | wc -l) ];then
        printf "\033[0;33m[waring] $module に対応するbcsymbolmapが見つかりませんでした.\033[0m\n"
        continue
    fi
    printBcsymbolmapFiles | grep $module
done
