#!/bin/bash
TOKEN=${GITHUB_ACCESS_TOKEN:?"GitHub Personal Access Token is required."}
NUMBER=${1:?}
MESSAGE=${2:-"👌"}
USER_REPO=$(git remote -v | head -1 | sed 's,.*github.com[:/],,; s/ (fetch)$//; s/\.git$//')
DATA=$(cat <<EOF
{
    "event": "APPROVE",
    "body": "${MESSAGE}"
}
EOF
)
curl -sS -H "Authorization: token ${TOKEN}" \
    https://api.github.com/repos/${USER_REPO}/pulls/${NUMBER}/reviews \
    -d "${DATA}" \
    | jq .body
