#!/bin/bash
# Get bearer token for TwitterAPI
# SeeAlso: https://dev.twitter.com/oauth/application-only
CONSUMER_KEY=${1}
CONSUMER_SECRET=${2}
CONSUMER_KEY=$(echo -n $CONSUMER_KEY | cmdshelf run net/url_encode)
CONSUMER_SECRET=$(echo -n $CONSUMER_SECRET | cmdshelf run net/url_encode)
REQUEST=$(echo -n "${CONSUMER_KEY}:${CONSUMER_SECRET}" | base64)

DATA=grant_type=client_credentials
JSON=$(curl -sSL https://api.twitter.com/oauth2/token -d "${DATA}" \
    -H "Authorization:Basic ${REQUEST}" \
    -H "Content-Type:application/x-www-form-urlencoded;charset=UTF-8")

TYPE=$(echo "$JSON" | jq .token_type | sed 's/"//g')
if [ $TYPE != "bearer" ];then
    echo Response token_type was not bearer: $JSON
    exit 1
fi
echo -n $JSON | jq .access_token | sed 's/"//g'

